name: CI Test
on:
  push:
    branches:
      - master
jobs:
  build-and-prerelease:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
          scope: '@picgo'
      - name: pnpm install, make tests
        run: |
          pnpm install
          pnpm run build
          pnpm run test
      - name: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_NEW_TOKEN }}